language: python

python:
  - 2.7

git:
  depth: 3

install:
  - pip install -r requirements.txt

env:
  - DEBUG=true

script:
  - python setup.py test
  - python setup.py install
  - unlocker -h
  - unlocker init
  - unlocker addons
  - unlock help
  - lock help
  - make tests
