language: python

python:
  - 2.7

git:
  depth: 3

install:
  - pip install -r requirements.txt

script:
  - python setup.py test
  - python setup.py install
  - unlocker -h
  - DEBUG=true unlocker init
  - DEBUG=true unlocker install
  - unlock help
  - lock help
  - make tests
